/* ============================================================
   Triple 7 Holdings — demo inventory
   ------------------------------------------------------------
   PLACEHOLDER DATA. Stands in for Person 2's Supabase `products`
   table until it is live. Every field name here matches the
   column names documented in COMMERCE.md — when the real table
   exists, js/api.js reads from Supabase instead and this file is
   deleted. Nothing else in the commerce code reads it directly.

   A diamond is a unique item: one row = one physical stone, so
   `qty` is always 1 and `status` gates whether it can be bought.
   ============================================================ */
window.T7_SEED = [
  { sku:'T7-MX-1041', title:'Maxwill Brilliant',      type:'polished', shape:'round',    carat:1.02, colour:'D', clarity:'VS1',  cut:'Excellent', polish:'Excellent', symmetry:'Excellent', fluorescence:'None',   measurements:'6.48 × 6.51 × 3.99 mm', certificate_lab:'GIA', certificate_no:'2417 883 041', origin_mine:'Maxwill Mine',       price_zar:168500,  status:'available' },
  { sku:'T7-MX-1077', title:'Maxwill Princess',       type:'polished', shape:'princess', carat:1.51, colour:'F', clarity:'VVS2', cut:'Excellent', polish:'Excellent', symmetry:'Very Good', fluorescence:'Faint',  measurements:'6.21 × 6.18 × 4.42 mm', certificate_lab:'GIA', certificate_no:'2417 883 077', origin_mine:'Maxwill Mine',       price_zar:243900,  status:'available' },
  { sku:'T7-MX-1108', title:'Douglas Oval',           type:'polished', shape:'oval',     carat:0.74, colour:'E', clarity:'VS2',  cut:'Very Good', polish:'Excellent', symmetry:'Very Good', fluorescence:'None',   measurements:'6.92 × 4.88 × 3.02 mm', certificate_lab:'HRD', certificate_no:'HRD-118 402',  origin_mine:'Maxwill Mine',       price_zar:94200,   status:'available' },
  { sku:'T7-MX-1130', title:'Maxwill Emerald',        type:'polished', shape:'emerald',  carat:2.03, colour:'G', clarity:'VS1',  cut:'Excellent', polish:'Very Good', symmetry:'Excellent', fluorescence:'None',   measurements:'8.44 × 6.02 × 3.94 mm', certificate_lab:'GIA', certificate_no:'2417 884 130', origin_mine:'Maxwill Mine',       price_zar:389000,  status:'reserved'  },

  { sku:'T7-BK-2012', title:'Bucklands Cushion',      type:'polished', shape:'cushion',  carat:1.28, colour:'F', clarity:'SI1',  cut:'Very Good', polish:'Very Good', symmetry:'Good',      fluorescence:'Medium', measurements:'6.44 × 6.30 × 4.11 mm', certificate_lab:'IGI', certificate_no:'IGI-620 112',  origin_mine:'Bucklands Mine',     price_zar:132400,  status:'available' },
  { sku:'T7-BK-2044', title:'Bucklands Pear',         type:'polished', shape:'pear',     carat:0.91, colour:'D', clarity:'VVS1', cut:'Excellent', polish:'Excellent', symmetry:'Excellent', fluorescence:'None',   measurements:'8.01 × 5.24 × 3.28 mm', certificate_lab:'GIA', certificate_no:'2418 004 044', origin_mine:'Bucklands Mine',     price_zar:161700,  status:'available' },
  { sku:'T7-BK-2069', title:'Bucklands Marquise',     type:'polished', shape:'marquise', carat:1.14, colour:'H', clarity:'VS2',  cut:'Very Good', polish:'Very Good', symmetry:'Very Good', fluorescence:'Faint',  measurements:'10.12 × 5.06 × 3.14 mm',certificate_lab:'HRD', certificate_no:'HRD-118 669',  origin_mine:'Bucklands Mine',     price_zar:108900,  status:'available' },
  { sku:'T7-BK-2090', title:'Bucklands Rough 4.6ct',  type:'rough',    shape:'rough',    carat:4.62, colour:'G', clarity:'VS',   cut:null,        polish:null,        symmetry:null,        fluorescence:null,     measurements:'11.4 × 9.8 × 8.6 mm',   certificate_lab:null,  certificate_no:null,           origin_mine:'Bucklands Mine',     price_zar:214000,  status:'available' },

  { sku:'T7-CH-3007', title:'Christiana Brilliant',   type:'polished', shape:'round',    carat:0.52, colour:'F', clarity:'VS1',  cut:'Excellent', polish:'Excellent', symmetry:'Excellent', fluorescence:'None',   measurements:'5.16 × 5.19 × 3.18 mm', certificate_lab:'GIA', certificate_no:'2418 110 007', origin_mine:'Christiana Mine',    price_zar:52800,   status:'available' },
  { sku:'T7-CH-3033', title:'Christiana Radiant',     type:'polished', shape:'radiant',  carat:1.71, colour:'G', clarity:'SI1',  cut:'Very Good', polish:'Excellent', symmetry:'Very Good', fluorescence:'Faint',  measurements:'7.22 × 6.04 × 4.28 mm', certificate_lab:'IGI', certificate_no:'IGI-620 833',  origin_mine:'Christiana Mine',    price_zar:186300,  status:'available' },
  { sku:'T7-CH-3058', title:'Christiana Oval',        type:'polished', shape:'oval',     carat:2.41, colour:'E', clarity:'VVS2', cut:'Excellent', polish:'Excellent', symmetry:'Excellent', fluorescence:'None',   measurements:'10.04 × 6.88 × 4.19 mm',certificate_lab:'GIA', certificate_no:'2418 110 058', origin_mine:'Christiana Mine',    price_zar:612000,  status:'available' },
  { sku:'T7-CH-3081', title:'Christiana Rough 7.1ct', type:'rough',    shape:'rough',    carat:7.14, colour:'H', clarity:'SI',   cut:null,        polish:null,        symmetry:null,        fluorescence:null,     measurements:'13.9 × 12.1 × 9.8 mm',  certificate_lab:null,  certificate_no:null,           origin_mine:'Christiana Mine',    price_zar:298500,  status:'sold'      },

  { sku:'T7-MD-4019', title:'Modican Brilliant',      type:'polished', shape:'round',    carat:1.00, colour:'G', clarity:'SI1',  cut:'Very Good', polish:'Very Good', symmetry:'Very Good', fluorescence:'Medium', measurements:'6.40 × 6.43 × 3.94 mm', certificate_lab:'IGI', certificate_no:'IGI-621 019',  origin_mine:'Modican Mine',       price_zar:88400,   status:'available' },
  { sku:'T7-MD-4042', title:'Modican Princess',       type:'polished', shape:'princess', carat:0.83, colour:'E', clarity:'VS2',  cut:'Excellent', polish:'Excellent', symmetry:'Very Good', fluorescence:'None',   measurements:'5.14 × 5.11 × 3.68 mm', certificate_lab:'HRD', certificate_no:'HRD-119 042',  origin_mine:'Modican Mine',       price_zar:97600,   status:'available' },
  { sku:'T7-MD-4066', title:'Modican Emerald',        type:'polished', shape:'emerald',  carat:1.36, colour:'H', clarity:'VS1',  cut:'Very Good', polish:'Very Good', symmetry:'Good',      fluorescence:'Faint',  measurements:'7.48 × 5.31 × 3.46 mm', certificate_lab:'IGI', certificate_no:'IGI-621 066',  origin_mine:'Modican Mine',       price_zar:119800,  status:'available' },
  { sku:'T7-MD-4094', title:'Modican Rough 3.2ct',    type:'rough',    shape:'rough',    carat:3.21, colour:'I', clarity:'SI',   cut:null,        polish:null,        symmetry:null,        fluorescence:null,     measurements:'9.6 × 8.4 × 7.1 mm',    certificate_lab:null,  certificate_no:null,           origin_mine:'Modican Mine',       price_zar:126000,  status:'available' },

  { sku:'T7-TK-5011', title:'Thaba Kholo Cushion',    type:'polished', shape:'cushion',  carat:3.02, colour:'F', clarity:'VS2',  cut:'Excellent', polish:'Excellent', symmetry:'Excellent', fluorescence:'None',   measurements:'8.61 × 8.44 × 5.52 mm', certificate_lab:'GIA', certificate_no:'2418 220 011', origin_mine:'Thaba Kholo',        price_zar:848000,  status:'available' },
  { sku:'T7-TK-5038', title:'Thaba Kholo Pear',       type:'polished', shape:'pear',     carat:1.62, colour:'D', clarity:'VS1',  cut:'Excellent', polish:'Excellent', symmetry:'Very Good', fluorescence:'None',   measurements:'9.84 × 6.42 × 4.02 mm', certificate_lab:'GIA', certificate_no:'2418 220 038', origin_mine:'Thaba Kholo',        price_zar:344700,  status:'available' },
  { sku:'T7-TK-5052', title:'Thaba Kholo Brilliant',  type:'polished', shape:'round',    carat:0.68, colour:'I', clarity:'SI2',  cut:'Good',      polish:'Very Good', symmetry:'Good',      fluorescence:'Strong', measurements:'5.62 × 5.66 × 3.48 mm', certificate_lab:'IGI', certificate_no:'IGI-622 052',  origin_mine:'Thaba Kholo',        price_zar:41300,   status:'available' },
  { sku:'T7-TK-5075', title:'Thaba Kholo Rough 11ct', type:'rough',    shape:'rough',    carat:11.08,colour:'G', clarity:'VS',   cut:null,        polish:null,        symmetry:null,        fluorescence:null,     measurements:'16.2 × 14.4 × 11.9 mm', certificate_lab:null,  certificate_no:null,           origin_mine:'Thaba Kholo',        price_zar:742000,  status:'available' },

  { sku:'T7-SP-6003', title:'Sepelong Marquise',      type:'polished', shape:'marquise', carat:0.88, colour:'F', clarity:'VS2',  cut:'Very Good', polish:'Very Good', symmetry:'Very Good', fluorescence:'None',   measurements:'9.42 × 4.71 × 2.94 mm', certificate_lab:'HRD', certificate_no:'HRD-119 503',  origin_mine:'Sepelong Game Farm', price_zar:79400,   status:'available' },
  { sku:'T7-SP-6027', title:'Sepelong Radiant',       type:'polished', shape:'radiant',  carat:1.19, colour:'G', clarity:'VS1',  cut:'Excellent', polish:'Excellent', symmetry:'Excellent', fluorescence:'Faint',  measurements:'6.44 × 5.38 × 3.81 mm', certificate_lab:'GIA', certificate_no:'2418 330 027', origin_mine:'Sepelong Game Farm', price_zar:141200,  status:'available' },
  { sku:'T7-SP-6049', title:'Sepelong Oval',          type:'polished', shape:'oval',     carat:1.85, colour:'H', clarity:'SI1',  cut:'Very Good', polish:'Very Good', symmetry:'Good',      fluorescence:'Medium', measurements:'9.12 × 6.08 × 3.77 mm', certificate_lab:'IGI', certificate_no:'IGI-622 449',  origin_mine:'Sepelong Game Farm', price_zar:158600,  status:'available' },
  { sku:'T7-SP-6081', title:'Sepelong Brilliant',     type:'polished', shape:'round',    carat:4.11, colour:'E', clarity:'VVS1', cut:'Excellent', polish:'Excellent', symmetry:'Excellent', fluorescence:'None',   measurements:'10.18 × 10.22 × 6.28 mm',certificate_lab:'GIA',certificate_no:'2418 330 081', origin_mine:'Sepelong Game Farm', price_zar:1980000, status:'available' }
];
